# 📝 Práctica M04: Gestión y Limpieza de Cartera Hipotecaria

**Escenario:** Has recibido tres fuentes de datos distintas sobre una pequeña cartera de préstamos. Los datos están desordenados, faltan valores y necesitas consolidarlos para presentar un informe de riesgo a tu responsable.

**Ejercicio 0:** Preparación de los Datos

Ejecuta la siguiente celda para cargar los DataFrames base con los que trabajarás.

In [1]:
import pandas as pd
import numpy as np

# Datos de clientes
clientes_master = pd.DataFrame({
    'ID_Cliente': [f'C-{str(i).zfill(3)}' for i in range(1, 21)],
    'Nombre': [
        'Juan Perez', 'Ana Diaz', 'Luis Ruiz', 'Marta Soto', 'Carlos Gil',
        'Elena Sanz', 'Pedro Gomez', 'Lucia Fernandez', 'Jorge Lopez', 'Maria Garcia',
        'Raul Castro', 'Sofia Martin', 'Andres Molina', 'Paula Vazquez', 'Hugo Ramos',
        'Isabel Torres', 'Miguel Angel', 'Carmen Ortiz', 'Javier Cano', 'Beatriz Rubio'
    ],
    'Ingresos': [3500, np.nan, 4200, 2800, np.nan, 3100, 2900, 5000, 4500, np.nan, 
                 3300, 4100, 2700, 2400, 6000, 3800, 3200, 2100, 4800, 1200],
    'Sucursal': ['Norte', 'Sur', 'Norte', 'Este', 'Sur', 'Norte', 'Sur', 'Este', 'Oeste', 'Norte',
                  'Sur', 'Norte', 'Este', 'Oeste', 'Sur', 'Norte', 'Este', 'Oeste', 'Sur', 'Norte'],
    'Empleo': ['Analista', 'Gerente', 'Analista', 'Cajero', 'Director', 'Analista', 'Cajero', 'Consultor', 'Gerente', 'Analista', 
               'Desarrollador', 'Gerente', 'Analista', 'Soporte', 'Director', 'Consultor', 'Analista', 'Vendedor', 'Gerente', 'Becario'],
    'Edad': [50, 36, 29, 42, 40, 28, 44, 30, 55, 33, 41, 25, 47, 39, 52, 27, 31, 45, 34, 23],
    'Ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Sevilla', 'Valencia', 'Madrid', 'Bilbao', 'Valencia', 'Madrid', 'Zaragoza',
                'Malaga', 'Sevilla', 'Madrid', 'Alicante', 'Murcia', 'Gijon', 'Madrid', 'Santiago', 'Granada', 'Toledo']
})

# Datos del Préstamo
prestamos_data = pd.DataFrame({
    'ID_Cliente': [f'C-{str(i).zfill(3)}' for i in range(1, 21)],
    'Saldo_Pendiente': [120000, 85000, 250000, 10000, 95000, 45000, 130000, 210000, 0, 55000,
                        88000, 15000, 110000, 67000, 290000, 12000, 43000, 0, 180000, 5000],
    'Cuotas_Impagadas': [0, 1, 0, 3, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0]
})
clientes_master.head()

  ID_Cliente      Nombre  Ingresos Sucursal    Empleo  Edad     Ciudad
0      C-001  Juan Perez    3500.0    Norte  Analista    50     Madrid
1      C-002    Ana Diaz       NaN      Sur   Gerente    36  Barcelona
2      C-003   Luis Ruiz    4200.0    Norte  Analista    29     Madrid
3      C-004  Marta Soto    2800.0     Este    Cajero    42    Sevilla
4      C-005  Carlos Gil       NaN      Sur  Director    40   Valencia

## 🛠️ EJERCICIOS

**Ejercicio 1:** Consolidación (Merge)

Crea un nuevo DataFrame llamado df_cartera uniendo clientes_master y prestamos_data a través de su columna común.

In [3]:
df_cartera = pd.merge(clientes_master, prestamos_data, on = 'ID_Cliente' )
df_cartera
#Primero buscamos cual es su columna común, 
#observamos que es el ID del cliente y usar eso como parámetro 'on'

,ID_Cliente,Nombre,Ingresos,Sucursal,Empleo,Edad,Ciudad,Saldo_Pendiente,Cuotas_Impagadas
0,C-001,Juan Perez,3500.0,Norte,Analista,50,Madrid,120000,0
1,C-002,Ana Diaz,NaN,Sur,Gerente,36,Barcelona,85000,1
2,C-003,Luis Ruiz,4200.0,Norte,Analista,29,Madrid,250000,0
3,C-004,Marta Soto,2800.0,Este,Cajero,42,Sevilla,10000,3
4,C-005,Carlos Gil,NaN,Sur,Director,40,Valencia,95000,0
5,C-006,Elena Sanz,3100.0,Norte,Analista,28,Madrid,45000,0
6,C-007,Pedro Gomez,2900.0,Sur,Cajero,44,Bilbao,130000,1
7,C-008,Lucia Fernandez,5000.0,Este,Consultor,30,Valencia,210000,0
8,C-009,Jorge Lopez,4500.0,Oeste,Gerente,55,Madrid,0,0
9,C-010,Maria Garcia,NaN,Norte,Analista,33,Zaragoza,55000,2
10,C-011,Raul Castro,3300.0,Sur,Desarrollador,41,Malaga,88000,0
11,C-012,Sofia Martin,4100.0,Norte,Gerente,25,Sevilla,15000,0
12,C-013,Andres Molina,2700.0,Este,Analista,47,Madrid,110000,1
13,C-014,Paula Vazquez,2400.0,Oeste,Soporte,39,Alicante,67000,0
14,C-015,Hugo Ramos,6000.0,Sur,Director,52,Murcia,290000,0
15,C-016,Isabel Torres,3800.0,Norte,Consultor,27,Gijon,12000,0
16,C-017,Miguel Angel,3200.0,Este,Analista,31,Madrid,43000,1
17,C-018,Carmen Ortiz,2100.0,Oeste,Vendedor,45,Santiago,0,0
18,C-019,Javier Cano,4800.0,Sur,Gerente,34,Granada,180000,2
19,C-020,Beatriz Rubio,1200.0,Norte,Becario,23,Toledo,5000,0

**Ejercicio 2:** Tratamiento de Nulos (Fillna)

Existen ingresos faltantes en la cartera.
1. Calcula la mediana de los ingresos de la columna Ingresos.
2. Rellena los valores nulos del df_cartera con esa mediana. No queremos borrar clientes, queremos estimar su capacidad.

In [ ]:
mediana_ingrs = df_cartera['Ingresos'].median()
#Simple uso de la función .median() para calcular la mediana de la columna pedida.
df_cartera['Ingresos'] = df_cartera['Ingresos'].fillna(mediana_ingrs)
# Reasignamos la columna con los valores rellenados

#Otra forma válida (se desaconseja cada vez más el uso de inplace) :
df_cartera.fillna({'Ingresos': mediana_ingrs}, inplace = True)
#Con fillna indicamos que vamos a rellenar nulos en df_cartera
#y le indicaremos a la función que será en la columna ingresos con el 
#valor calculado en el parámetro de la mediana
#inplace true para que se formalice en la tabla original este cambio

,ID_Cliente,Nombre,Ingresos,Sucursal,Empleo,Edad,Ciudad,Saldo_Pendiente,Cuotas_Impagadas
0,C-001,Juan Perez,3500.0,Norte,Analista,50,Madrid,120000,0
1,C-002,Ana Diaz,3300.0,Sur,Gerente,36,Barcelona,85000,1
2,C-003,Luis Ruiz,4200.0,Norte,Analista,29,Madrid,250000,0
3,C-004,Marta Soto,2800.0,Este,Cajero,42,Sevilla,10000,3
4,C-005,Carlos Gil,3300.0,Sur,Director,40,Valencia,95000,0
5,C-006,Elena Sanz,3100.0,Norte,Analista,28,Madrid,45000,0
6,C-007,Pedro Gomez,2900.0,Sur,Cajero,44,Bilbao,130000,1
7,C-008,Lucia Fernandez,5000.0,Este,Consultor,30,Valencia,210000,0
8,C-009,Jorge Lopez,4500.0,Oeste,Gerente,55,Madrid,0,0
9,C-010,Maria Garcia,3300.0,Norte,Analista,33,Zaragoza,55000,2
10,C-011,Raul Castro,3300.0,Sur,Desarrollador,41,Malaga,88000,0
11,C-012,Sofia Martin,4100.0,Norte,Gerente,25,Sevilla,15000,0
12,C-013,Andres Molina,2700.0,Este,Analista,47,Madrid,110000,1
13,C-014,Paula Vazquez,2400.0,Oeste,Soporte,39,Alicante,67000,0
14,C-015,Hugo Ramos,6000.0,Sur,Director,52,Murcia,290000,0
15,C-016,Isabel Torres,3800.0,Norte,Consultor,27,Gijon,12000,0
16,C-017,Miguel Angel,3200.0,Este,Analista,31,Madrid,43000,1
17,C-018,Carmen Ortiz,2100.0,Oeste,Vendedor,45,Santiago,0,0
18,C-019,Javier Cano,4800.0,Sur,Gerente,34,Granada,180000,2
19,C-020,Beatriz Rubio,1200.0,Norte,Becario,23,Toledo,5000,0

**Ejercicio 3:** Feature Engineering (Nuevas Métricas)

Crea una columna llamada Nivel_Riesgo.
1. Si un cliente tiene Cuotas_Impagadas > 0, su nivel de riesgo es "Alto".
2. De lo contrario, es "Bajo". (Pista: Puedes usar .apply() con una función lambda o np.where()).

In [ ]:
df_cartera['Nivel_Riesgo']= np.where(df_cartera['Cuotas_Impagadas']>0, 'Alto', 'Bajo')
#where recibe trs parámetros: 1.Condición a evaluar 2.Valor si verdadero 3.Valor si falso
#Creamos un condicional dentro del where donde le damos los dos valores posibles
#Python recorre toda la columna comprobando la condición y asigna valores
df_cartera.head()

,ID_Cliente,Nombre,Ingresos,Sucursal,Empleo,Edad,Ciudad,Saldo_Pendiente,Cuotas_Impagadas,Nivel_Riesgo
0,C-001,Juan Perez,3500.0,Norte,Analista,50,Madrid,120000,0,Bajo
1,C-002,Ana Diaz,3300.0,Sur,Gerente,36,Barcelona,85000,1,Alto
2,C-003,Luis Ruiz,4200.0,Norte,Analista,29,Madrid,250000,0,Bajo
3,C-004,Marta Soto,2800.0,Este,Cajero,42,Sevilla,10000,3,Alto
4,C-005,Carlos Gil,3300.0,Sur,Director,40,Valencia,95000,0,Bajo

In [ ]:
Calculo_Riesgo= lambda Impagos: 'Alto' if Impagos > 0 else 'Bajo'
df_cartera['Nivel_Riesgo']= df_cartera['Cuotas_Impagadas'].apply(Calculo_Riesgo)
#Con .apply() aplicamos una función matemática personalizada o regla de negocio a cada
#celda de una columna en concreto. 
#Creamos una expresión lambda para aplicarla después
#Recorremos la columna aplicando la lambda expression a cada valor

In [ ]:
df_cartera['Nivel_Riesgo'] = 'Bajo'
df_cartera.loc[df_cartera['Cuotas_Impagadas'] > 0, 'Nivel_Riesgo'] = 'Alto'
#Usamos el indexador bidimensional .loc para decirle que queremos las filas
#que cumplan nuestra condición y la columna del nivel de riesgo

**Ejercicio 4:** Recuento

¿Cuál es el empleo que más se repite en nuestra base de datos?

In [62]:
Numero_Empleos=df_cartera.groupby('Empleo')['Empleo'].count()
Empleo_Mas_Repetido = Numero_Empleos.idxmax()
print(f"El empleo más común es: {Empleo_Mas_Repetido}")

El empleo más común es: Analista

In [ ]:
trabajo_comun = df_cartera['Empleo'].value_counts().idxmax()
#value_counts nos ahora hacer groupby('x')['x'].count() pues hace todo esto
#en una sola instrucción, devolviendo una serie de pandas a la cual 
#le aplicamos idxmax() para que nos de cual es
#el indice que mas se repite y lo sacamos por pantalla
print(f"El trabajo más común es: {trabajo_comun}")

El trabajo más común es: Analista

**Ejercicio 5:** Diversidad laboral

¿Cuántos trabajos distintos existen en el dataset?

In [ ]:
Trabajos_Dist = df_cartera['Empleo'].nunique()
# .nunique() devuelve el número de objetos diferentes que hay en el objeto
print(f"Hay {Trabajos_Dist} trabajos distintos en nuestro dataset")

Hay 9 trabajos distintos en nuestro dataset

**Ejercicio 6:** Ciudades únicas

¿Qué ciudades aparecen exactamente una sola vez?

In [ ]:
Conteos_Ciudad = df_cartera['Ciudad'].value_counts()
#Sacamos una pd.serie de el número de clientes que tiene cada ciudad
Ciudades_Unicas = Conteos_Ciudad[Conteos_Ciudad==1].index.tolist()
#Buscamos las que solo tienen un único cliente y sacamos los índices de este df
#y lo pasamos a una lista que devolvemos por pantalla
print(f"Las ciudades que aparecen de forma única son: {Ciudades_Unicas}")

Las ciudades que aparecen de forma única son: ['Barcelona', 'Bilbao', 'Zaragoza', 'Malaga', 'Alicante', 'Murcia', 'Gijon', 'Santiago', 'Granada', 'Toledo']

**Ejercicio 7:** Búsqueda por nombre

Identifica a todas las personas que tengan la letra "u" (mayúscula o minúscula) en su nombre.

In [ ]:
contiene_u = df_cartera[df_cartera['Nombre'].str.contains("u", case = False)]
#Usamos .str para que la pd.series devuelta por la selección sea tratada como un string
#y así podamos aplicarle la función .contains a la cual le indicaremos 
#que no sea case sensitive en este caso específico
print("Clientes con 'u' en su nombre: ")
print(contiene_u['Nombre'])
#Filtramos de la tabla de los clientes para obtener solo su nombre y 
#no el resto de su información irrelevante.

Clientes con 'u' en su nombre:
0          Juan Perez
2           Luis Ruiz
7     Lucia Fernandez
10        Raul Castro
13      Paula Vazquez
14         Hugo Ramos
16       Miguel Angel
19      Beatriz Rubio
Name: Nombre, dtype: str

**Ejercicio 8:** Correlación

Calcula la correlación entre la Edad y los Ingresos. ¿Existe alguna relación lineal?

In [ ]:
correlacion = df_cartera['Edad'].corr(df_cartera['Ingresos'])
#De este modo calcula una correlacion unica, lo que devuelve un número,
#para calcular otras podemos hacer
# 1.) Entre varios parámetros entre si, lo que devuelve un df (matriz correlación): 
#     df_cartera[['Edad','Ingresos','Cuotas_Impagadas']].corr()

# 2.) Un parámetro frente al resto del df, lo que devuelve una pd.series: 
#       1. df_cartera.corr()['Cuotas_Impagadas'] 
#       2. df_cartera.corrwith(df_cartera['Cuotas_Impagadas'])
print(f"La correlación entre edad e ingresos es: {correlacion:.2f}")

La correlación entre edad e ingresos es: 0.17

**Ejercicio 9:** Análisis Agregado (GroupBy)

¿Cuál es el Saldo_Pendiente total y el Ingreso promedio por cada Sucursal? Presenta una tabla resumen.

In [ ]:
df_cartera.groupby('Sucursal').agg({
    'Saldo_Pendiente' : 'sum',
    'Ingresos' : 'mean'
})
#Primero agrupamos por sucursales que es lo que nos piden,
#después usamos .agg() que acepta el paso de diccionarios con
#estructura {'Nombre_Col': 'Operacion_Mat'}, además
#podríamos pasarle una lista como operaciones para una columna.
# ... 'Ingresos' : ['mean','max']... })

         Saldo_Pendiente     Ingresos
                     sum         mean     max
Sucursal
Este              373000  3425.000000  5000.0
Norte             502000  3316.666667  4200.0
Oeste              67000  3000.000000  4500.0
Sur               868000  4250.000000  6000.0

**Ejercicio 10:** Selección Crítica

Muestra únicamente los datos de los clientes de la sucursal "Sur" que tengan un Saldo_Pendiente mayor a 90.000€.

In [ ]:
Sucursal_Sur_High = df_cartera[(df_cartera['Sucursal']=='Sur') & (df_cartera['Saldo_Pendiente'] > 90000)]
#Puesto que se nos piden valores centrales dentro de la tabla debemos hacer un filtrado doble
#como si de una intersección en teoría de conjuntos se tratase.
print("\n --- Alerta Clientes Sucursal Sur con alto Saldo Pendiente---")
print(Sucursal_Sur_High)

 --- Alerta Clientes Sucursal Sur con alto Saldo Pendiente---
   ID_Cliente       Nombre  Ingresos Sucursal    Empleo  Edad    Ciudad  \
4       C-005   Carlos Gil       NaN      Sur  Director    40  Valencia
6       C-007  Pedro Gomez    2900.0      Sur    Cajero    44    Bilbao
14      C-015   Hugo Ramos    6000.0      Sur  Director    52    Murcia
18      C-019  Javier Cano    4800.0      Sur   Gerente    34   Granada

    Saldo_Pendiente  Cuotas_Impagadas
4             95000                 0
6            130000                 1
14           290000                 0
18           180000                 2

## ✅ SOLUCIONES

In [ ]:
# 1. Merge
df = pd.merge(clientes_master, prestamos_data, on='ID_Cliente')

# 2. Imputación de nulos
mediana_ingr = df['Ingresos'].median()
df['Ingresos'].fillna(mediana_ingr, inplace=True)

# 3. Clasificación de riesgo
df['Nivel_Riesgo'] = df['Cuotas_Impagadas'].apply(lambda x: 'Alto' if x > 0 else 'Bajo')

# 4. Trabajo más común
trabajo_comun = df['Empleo'].value_counts().idxmax()
print(f"El trabajo más común es: {trabajo_comun}")

# 5. Cantidad de trabajos distintos
total_empleos = df['Empleo'].nunique()
print(f"Hay {total_empleos} tipos de empleos diferentes.")

# 6. Ciudades que aparecen solo una vez
conteos_ciudades = df['Ciudad'].value_counts()
ciudades_unicas = conteos_ciudades[conteos_ciudades == 1].index.tolist()
print(f"Ciudades con un solo cliente: {ciudades_unicas}")

# 7. Personas con una "u" en su nombre
con_u = df[df['Nombre'].str.contains('u', case=False)]
print("Clientes con 'u' en su nombre:")
print(con_u[['Nombre']])

# 8. Correlación entre Edad e Ingresos
# Nota: corr() ignora los valores NaN automáticamente
correlacion = df['Edad'].corr(df['Ingresos'])
print(f"La correlación entre Edad e Ingresos es: {correlacion:.2f}")

# 9. Agregación por sucursal
resumen_sucursales = df_cartera.groupby('Sucursal').agg({
    'Saldo_Pendiente': 'sum',
    'Ingresos': 'mean'
})

# 10. Filtrado condicional
filtro_sur_high = df_cartera[(df_cartera['Sucursal'] == 'Sur') & (df_cartera['Saldo_Pendiente'] > 90000)]

# Visualización de resultados finales
print("--- Cartera Consolidada ---")
print(df_cartera)
print("\n--- Resumen por Sucursal ---")
print(resumen_sucursales)
print("\n--- Alerta Clientes Sur con Alto Saldo ---")
print(filtro_sur_high)